version: "3.8"
services: 
  nginx:
    image: nginx:1.19
    ports:
      - 8080:80
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
     image: php:7.4-apache
     volumes:
      - ./php:/var/www/html:ro